'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { UserContext } from "./context/UserContext";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <UserContext>
          <Suspense fallback={`${<div className="flex min-h-screen items-center justify-center">
                                <span className="loading loading-spinner loading-lg text-success"></span>
                              </div>}`
          }>
            <Navbar></Navbar>
            <main>{children}</main>
          </Suspense>
        </UserContext>
      </body>
    </html>
  );
}
